### ISSUE TITLE
Regex pattern determination

### ISSUE THREAD

**Issue by devinvisible** [veiset/poe-vendor-string#100]
Please excuse me for abusing github's "Issue" system -- this isn't actually an issue but a question:

I was curious if there was a tool / script for coming up with the short regex patterns used in matching items/beasts/etc. For example, given the full set of beast names, knowing that `d bri` matches "Wild Bristle Matron" and nothing else. I know the data set isn't that large but surely this wasn't done manually.

**Comment by veiset** [comment]
Hey, no worries!

The logic I use to generate the regex is basically brute-forcing the shortest unique string (some Kotlin code):

```kotlin
fun shortestUnique(query: String, modifiers: List<String>): String {
    val cleanQuery = query.cleanInput()
    val mods = modifiers.filter { it != query }.joinToString(" ")
        .cleanInput()

    val resultWithSpace = subStrings(cleanQuery).firstOrNull {
        !mods.contains(it)
                && !it.contains(Regex("[|\\n\\\\+]"))
                && !it.endsWith(" ")
    }
    val resultWithoutSpace = subStrings(cleanQuery).firstOrNull {
        !mods.contains(it)
                && !it.contains(" ")
                && !it.contains("-")
                && !it.contains("|")
                && !it.contains("\\")
                && !it.contains("+")
                && !it.endsWith(" ")
    }
    val spaceLength = resultWithSpace?.length ?: 1000
    val nospaceLength = resultWithoutSpace?.length ?: 1000
    val regexResult = if (nospaceLength <= spaceLength + 2) resultWithoutSpace else "\"$resultWithSpace\""
    val finalResult = regexResult ?: query
    val finalWithoutNumbers = finalResult.replace("#", "\\\\d+")
    return if (finalWithoutNumbers.contains(" ") && !finalWithoutNumbers.startsWith("\"")) "\"$finalWithoutNumbers\"" else finalWithoutNumbers
}
```

For bestiary I use all the beasts (obviously), but also a list of rare names and beast types to generate the shortest regex!

**Comment by veiset** [comment]
Closing the issue, but just comment in this thread if there are any more questions regarding this, or just create a new issue if there are any other questions. 😁
