### ISSUE TITLE
Suggest adding feature: regex for maps name

### ISSUE THREAD

**Issue by md3848** [veiset/poe-vendor-string#102]
Suggest adding feature: regex for maps name

**Comment by veiset** [comment]
Would you typically use this together with the map mods regex, or is the use case generic?

**Comment by md3848** [comment]
First, I want to filter my favorite maps (regex-maps-name), so that I can easily select them and transfer them to Folder/stab-tab craft.
Then after crafting the maps, I use regex-mods and recraft maps with bad mods.

Your site is good for people who only have 1 favorite map and only spam one map, but for people like me, having this feature on your site (which I requested) is useful.

On your site, I prefer to have this feature in a separate tab; Because the [Map modifiers] tab It's busy right now!
![image](https://github.com/veiset/poe-vendor-string/assets/17591943/3a80038e-c669-484b-9d0a-c0928e832c19)

**Comment by vinhvizg1040** [comment]
I tried doing it, and it worked on my forked. Take it and try it for yourself.
![image](https://github.com/veiset/poe-vendor-string/assets/70787514/2c023e28-1cc7-41da-801d-74cc138c40f4)

**Comment by veiset** [comment]
Really really awesome stuff!! 😁 If you want you can make a PR and I'll fix up the merge conflicits from some other stuff I am currently working on.

**Comment by veiset** [comment]
You can check out the profile stuff in this PR:

https://github.com/veiset/poe-vendor-string/pull/105

**Comment by veiset** [comment]
Thanks. This is now live on poe.re! Let me know if you find any issues with the regex generated.
