### ISSUE TITLE
Suggestion for regex map, add rarity

### ISSUE THREAD

**Issue by ConKou** [veiset/poe-vendor-string#103]
Having a simple toggle to enable highlighting only rare / magic / normal maps. As is right now we have to edit it manually.

**Comment by veiset** [comment]
Yes. I'll add this.

**Comment by veiset** [comment]
What regex do you currently use to check for magic/rare/normal?

**Comment by ConKou** [comment]
Ok so say my regex (produced from your site) is this:
```"!non|tal d|s ac|eec|f ph"```
I would add "|normal" in the end to make it highlight only rare maps:
```"!non|tal d|s ac|eec|f ph|normal"```
That way when rolling for maps with alc / scouring, maps that are not highlighted (they have bad mods) will stay unhighlighted when scouring.

**Comment by veiset** [comment]
Fixed in https://github.com/veiset/poe-vendor-string/pull/108, should be live now.
