### ISSUE TITLE
Suggestion: Magic crafting section

### ISSUE THREAD

**Issue by Blemming** [veiset/poe-vendor-string#104]
It could be interesting to have a section to generate a regex to craft magic items. With the new adorned jewel or just crafters getting good magic bases is pretty important to start the item. 

I could see this using the prefix and suffix name instead of exactly the mod you are looking for. Say you want a weapon with t1 phys damage you would add `merc` to the regex because the prefix name is merciless. 

Shout out to Palsteron for the idea, he does this manually in his video right here: https://youtu.be/RlICh3uYFYw?si=jL6dW2OJ2hB4WCa4&t=509

I know this is not a small task. Having all the possible mods for all the possible items and correctly showing the mods that are applicable for the appropriate item is a lot of work, without even associating those mods to their prefix/suffix names. Maybe we could start with juste magic jewels specifically for the adorned unique jewel and build from there ?

**Comment by veiset** [comment]
Good suggestion! This is something I will look at after adding map names and charged compasses.

**Comment by ogurisan** [comment]
please add like maximum life maximum mana those affix regex  for magic jewel
please please

**Comment by veiset** [comment]
Alright this is now implemented. This was a lot of work, but its finally live at: https://poe.re/#/jewel 

Let me know if there are any bugs with it, its a lot of moving parts so there might be some issues. I've tested and it looks good.
