### ISSUE TITLE
Support for regex search on map modifiers (paste regex to highlight mods)

### ISSUE THREAD

**Issue by md3848** [veiset/poe-vendor-string#110]
hi again :)
I have a regex (for example, my friend gave it to me or I found it on the internet), now I want to see what mods this regex contains, please add this feature to the site; so that I can enter the regex to the site and see all the information of that regex (exactly the opposite of what your site is doing now)

regex ---> information
A|B|C|D ----> AAAA, BBBB, CCCC, DDDD

**Comment by veiset** [comment]
This requires _a lot_ of work, and to rewrite big parts of the webpage, especially for the vendor section, so I won't implement this I'm afraid. The map section is easier to reverse.

**Comment by md3848** [comment]
ye i need this feture only for map mods :)

**Comment by veiset** [comment]
Would it be good enough to be able to paste the regex in to the search bar, and the mods would be filtered in the result? Because I think I can make that happen reasonable easy.

**Comment by md3848** [comment]
Yes, that's enough

**Comment by veiset** [comment]
![image](https://github.com/veiset/poe-vendor-string/assets/329529/79093d4f-32b9-4fc1-a7ea-eaf070da114b)

This is live now. Let me know if there are any issues.

You can copy any regex generated from the map mods page in to the search bar, and it should display the selected mods.

It also works if you've selected mods in either selection:

![image](https://github.com/veiset/poe-vendor-string/assets/329529/e7fe2dd1-3bf0-48b9-ac30-00fc476e3744)

**Comment by md3848** [comment]
tyvm sir.
