### ISSUE TITLE
Flask "Gain # Charges" regex is wrong

### ISSUE THREAD

**Issue by Jrribas** [veiset/poe-vendor-string#111]
Hello,

Gain # Charges when you are Hit by an Enemy should be this "s whe" instead of  "s wh" as flasks have in the description: "... hold charges while...".

**Comment by veiset** [comment]
I'll look in to this ASAP.

**Comment by veiset** [comment]
Yeah, this fixed a few issues.

```
     level: 61,
     name: "of the Beluga",
     value: "(46-50)% chance to Avoid being Chilled during Effect (46-50)% chance to Avoid being Frozen during Effect",
     regex: "elu" // old: bel
     
     minLevel: 12,
     description: "#% reduced Mana Cost of Skills during Effect",
     regex: "cos", // old: ls
     
     minLevel: 30,
     description: "Hinders nearby Enemies with #% reduced Movement Speed if used while not on Full Mana",
     regex: "l ma", // old: m l
     
```

**Comment by veiset** [comment]
Alright, this should be fixed now. Please let me know if this doesnt fix it.

I think the `Can only hold charges while in belt. Refills as you kill monsters` description on flasks is new this league, but I can't find any info about it. Thank you for reporting this and taking the time to figure out what was wrong!
