### ISSUE TITLE
reduced chance to block and less armor map mods got combined

### ISSUE THREAD

**Issue by ELepianka1** [veiset/poe-vendor-string#112]
![image](https://github.com/veiset/poe-vendor-string/assets/58861946/c709e2e7-a971-4b80-98bc-7405d6df5239)
looks like these 2 modifiers for chance to block and less armor got combined some how. clicking it only adds the chance to block regex so we're missing out on the less armor mod. i had to manually add it. should be separated.

**Comment by veiset** [comment]
It's the same mod. The mod has two lines, so if the regex matches the `chance to block` the map must also have `less armour`.  Atleast according to poedb:

![image](https://github.com/veiset/poe-vendor-string/assets/329529/d525691d-1e5f-49ad-8c7b-9fd1d80e6203)

There might be a bug on my side of things, can you share the map that was the issue? (ctrl+c, and paste the raw item data here)

**Comment by ELepianka1** [comment]
ah! you're correct. my apologies. on the PoE Trade site they are treated as 2 separate suffix mods which you can search on but i can't find one without the other so they're definitely a pair as the DB says.

**Comment by veiset** [comment]
Just verfied it should be working ingame, all these prompts give the same result:

![image](https://github.com/veiset/poe-vendor-string/assets/329529/a453a5f2-819a-4520-a0df-1201acb08eb6)

**Comment by veiset** [comment]
No worries!
