### ISSUE TITLE
[Beastcrafting] Incorrect regex for Elder-Blessed Retch

### ISSUE THREAD

**Issue by maciej-gol** [veiset/poe-vendor-string#113]
The current regex for "Elder-Blessed Retch" is `d re`. Unfortunately, it clashes with `Fast Energy Shield Recharge` affix, thus resulting in a lot of misses.

See image below:

![20240103094705_1](https://github.com/veiset/poe-vendor-string/assets/1861709/71eae428-82ad-4fa5-bb5f-e8863056e885)

**Comment by veiset** [comment]
Thanks for the report. I'll look in to this!

**Comment by veiset** [comment]
I've regenerated the regex basefile with `Fast Energy Shield Recharge` accounted for. The fix should be live in 5 mins, let me know if you find any other things with beasts.

The beast regex is pretty hard to keep correct, as they have so many monster names and monster modifiers.

**Comment by maciej-gol** [comment]
Worked, thanks <3 Also, thanks for quick response!
