### ISSUE TITLE
maps name bug 

### ISSUE THREAD

**Issue by md3848** [veiset/poe-vendor-string#114]
hi again, site give me this code 
"gle valley m|sland m"
```
Jungle Valley
and 
Tropical Island
```
when i use that code :
![image](https://github.com/veiset/poe-vendor-string/assets/17591943/a9db9fc7-2447-47b8-b161-56c227deeece)

when i remove " " : 
![image](https://github.com/veiset/poe-vendor-string/assets/17591943/78ca62e2-c8f8-410f-a86e-043fcc916c53)

**Comment by veiset** [comment]
This is an issue with the map tab :( 

The regex works differently for map tabs and stash tabs. The second regen wouldnt work correctly for a regular tab.

I guess the solution is to remove the quotes manually when searching a map tab.
