### ISSUE TITLE
[Request] bestiary regex 

### ISSUE THREAD

**Issue by pedrolopa** [veiset/poe-vendor-string#115]
Hello, few things about bestiary regex
1. recipe results seem to be wrong, many are "create a talisman"
2. It would be awesome if the regex could only include red beasts. I think some people, including myself, would like the use the regex to find beasts to delete (you usually only want to delete bad red beasts)
3. i had an issue with the regex "e re" for saqawine retch, showing a bunch of beasts. This seems to be because of some rare mods that can be on them, [like "life regen" or "fire resistant](https://imgur.com/a/SebcnqP)". changing it to "ne re" seems to have fixed it.
Thank you

**Comment by veiset** [comment]
Hey, regarding 3. - I've updated the regex with prefixes and suffixes based on this list: https://www.poewiki.net/wiki/Monster_modifiers


I hope that improves it. The beast-regex is still not the greatest. I'll try to make time to improve it further.

**Comment by willhuynh** [comment]
Hi, just one thing to note about the bestiary regex

It is different from any other type of regex as normally the character cap is 50, But for the bestiary it is 100.

I hope this is an easy fix, as it means I can make more currency, Thanks

**Comment by veiset** [comment]
oh, thats huge @willhuynh! I didnt know that, thats an easy fix on my part. I'll try to add it tomorrow.

**Comment by veiset** [comment]
@willhuynh fixed it in https://github.com/veiset/poe-vendor-string/commit/1144bb2af2585ee7048be29670598294a5fcf7f2 - should be live now. Let me know if you find any issues with it.

**Comment by veiset** [comment]
@pedrolopa fixed the talisman issue. Was an issue with ruthless recipies showing up. Updated in https://github.com/veiset/poe-vendor-string/commit/bd74238b87ea7e9968af61c7422f8057ca22f5b1

**Comment by veiset** [comment]
I'll close this for now as I have no clue how to filter red beasts. If anyone got any ideas feel free to make an new issue with a suggestion on how to solve it.

**Comment by willhuynh** [comment]
I mean you could manually look through the list of beasts for all of the red ones and remove the yellow ones but it could take a while, this is because most people don't look for yellow beasts when farming Einhar.

**Comment by pedrolopa** [comment]
"e re" for Saqawine Retch is still problematic

**Comment by pedrolopa** [comment]
also: Vivid Abberarach is considered a harvest beast by the regex, but actually it is not
thx great changes already
