### ISSUE TITLE
Remove Yellow Beasts from Bestiary Regex

### ISSUE THREAD

**Issue by willhuynh** [veiset/poe-vendor-string#117]
Since nobody trades for yellow beasts, I think that they should be removed entirely from the list.
You can use the wiki for the full list, Bold = Red beasts

https://www.poewiki.net/wiki/Bestiary

**Comment by veiset** [comment]
Thanks for the list. 

I've added an option to show red beasts only, can you do some testing and see if this solves it?

https://poe.re/#/beast

**Comment by willhuynh** [comment]
Thanks! That seems to do it

**Comment by veiset** [comment]
No worries. Please let me know if any red beasts are missing or wrong.
