### ISSUE TITLE
Collision between Less Recovery and map name "Godless Remains"

### ISSUE THREAD

**Issue by willlowther** [veiset/poe-vendor-string#12]
Item Class: Maps
Rarity: Rare
Godless Remains
Fields Map
--------
Map Tier: 14
Item Quantity: +75% (augmented)
Item Rarity: +33% (augmented)
Monster Pack Size: +21% (augmented)
Quality: +20% (augmented)
--------
Item Level: 83
--------
Players are Cursed with Vulnerability
Monsters have 100% increased Area of Effect
Unique Boss has 35% increased Life
Unique Boss has 70% increased Area of Effect
Unique Bosses are Possessed
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

------------------

This collided with the "ss r" generated by "Players have X% less Recovery Rate of Life and Energy Shield"

**Comment by veiset** [comment]
Thanks for the report. Good find! 👍 

The issue was the name `Godless Remains`, which matches `ss r`. I have fixed the issue and it should be live on the webpage now. Let me know if you find any other issues!
