### ISSUE TITLE
Suggestion regex: check armor bases: evasion / energy shield / armour

### ISSUE THREAD

**Issue by Asymat** [veiset/poe-vendor-string#123]
Example with 3 links AND evasion or boots with speed: `-\w- eva|nne|rint`

**Comment by veiset** [comment]
Hey, whats the use case for this?

It's also going to be real tricky if you select any color combination with an armour type.

**Comment by Asymat** [comment]
Because you can easily color gear with chromatic orbs. And also, to use different masteries. Ex: eva gear so I can have the 15% Suppress.

Yes, it is tricky for the regex and will use many chars...

**Comment by veiset** [comment]
Sorry, I wont be implement this as I can't figure out a non confusing way to implement this on the webpage. I can see this used for later in the game, but for early game suppression can't be rolled and you don't typically have extra chromes.
