### ISSUE TITLE
Max player res map modifier regex not working

### ISSUE THREAD

**Issue by Tillystix** [veiset/poe-vendor-string#125]
Regex lists "-#% maximum Player Resistances" but when selected will highlight maps with the mod "Players have -#% to all Maximum Resistances" 
![Maxplayerres](https://github.com/veiset/poe-vendor-string/assets/49132095/fcbfa4c9-34c8-4281-98b6-30790468d6f6)

**Comment by veiset** [comment]
Hey, thanks for the report, I'll fix this ASAP.

**Comment by veiset** [comment]
Alright, I found the issue.

The map mod `-#% maximum Player Resistances` has been renamed to `Players have -#% to all Maximum Resistances` ingame. 

New version is deployed, thanks for the report. Let me know if the fix doesn't solve the issue or you find anything else thats wrong.
