### ISSUE TITLE
Non-chanceable items in Gwennen Regex Generator

### ISSUE THREAD

**Issue by fa-se** [veiset/poe-vendor-string#126]
With 3.24, some items that were previously global drops and thus obtainable from Gwennen have been changed to boss drops. However, they seem to still be present in the Gwennen Regex Generator. One example of this is "Yoke of Suffering".

**Comment by veiset** [comment]
Hey, thanks for the report. I'll look in to this soon.

**Comment by veiset** [comment]
I've updated it now, thanks for the report. Let me know if you find some items that shouldnt show up.
