### ISSUE TITLE
[Request] Scarabs

### ISSUE THREAD

**Issue by SeeTwoDev** [veiset/poe-vendor-string#127]
With 3.24, there's so many scarabs. i'd like to make a regex for either lowest or highest value easily

**Comment by veiset** [comment]
That's a good idea. I'll start looking in to making that!

**Comment by SeeTwoDev** [comment]
Looks like you implemented it! Well done, thanks!

**Comment by veiset** [comment]
Hey, thanks! I just implemented it. Let me know if you find any bugs with it, I've tested it a bit but you never know.
