### ISSUE TITLE
Feature Suggestion: Sextants

### ISSUE THREAD

**Issue by Margonnite** [veiset/poe-vendor-string#13]
A Reg Ex generator for looking for specific compass mods would be amazingly helpful since there are dozens and dozens of mods and every compass looks exactly the same

**Comment by veiset** [comment]
I've been looking in to this but I don't understand the use case. 

Is there a way to roll sextants and highlight them at the same time? The watchstones wont get highlighted based on regex, but are you using loads of sextants and compasses, then searching for them?
