### ISSUE TITLE
Minus Max isn't catching in 3.24

### ISSUE THREAD

**Issue by visyx** [veiset/poe-vendor-string#130]
The string to catch it currently is '% ma', but the new wording is "Players have x% to all maximum resistances'.
![MinusMax](https://github.com/veiset/poe-vendor-string/assets/166266629/b8f9ad49-5e19-4695-8815-515eeb738218)

**Comment by Ynead** [comment]
Same for "Cannot Leech from Monsters".

**Comment by veiset** [comment]
@visyx Can you dobule check that this is the case? I solved this issue 3 days ago. Can you try to refresh the page?

The current regex for `-% to all max res` is `o al`:

<img width="580" alt="image" src="https://github.com/veiset/poe-vendor-string/assets/329529/35cce376-0541-46b8-97d0-13dcf1b954e7">

**Comment by veiset** [comment]
@Ynead whats the output you're using the check leech? It seems to be working here, so if you can expand on what you're doing I'll look in to it. Currently getting `eec` which seems to work. Are you trying it on any specific map?

**Comment by visyx** [comment]
@veiset I refreshed the page and now it's been corrected.  Thanks!
