### ISSUE TITLE
Map tag overlap between #% less Recovery Rate and #% less Cooldown Recovery Rate

### ISSUE THREAD

**Issue by wingot-git** [veiset/poe-vendor-string#132]
When selecting "Players have #% less Recovery Rate of Life and Energy Shield" as a map mod, the tag "reco" is added to the regex. However, this also registers for maps with "Players have #% less Cooldown Recovery Rate".

Issue is resolved with changing "reco" to "s reco", which seems the simplest and least likely to break with future changes, though conserving characters I note that "e an" doesn't hit any other tags either.

**Comment by veiset** [comment]
Good find. This is a bug with my regex generator. I'm currently looking in to it.

**Comment by veiset** [comment]
Actually, this was a bug introduced with the tier17 map modifiers. I've fixed it, should be live in 5 mins.
