### ISSUE TITLE
Range for resistances on flasks (rainbow suffix) is wrong.

### ISSUE THREAD

**Issue by Meisen1977** [veiset/poe-vendor-string#133]
poe.re -> flasks -> Only match suffix with the highest ilevel -> (37-40)% additional Elemental Resistances during Effect

That value is now incorrect. The correct range is 18-20%

P.S Sorry for bothering you on reddit :) Github fixed whatever their issue was, so i'm now posting the issue here.

**Comment by veiset** [comment]
Hey, thanks for the bug report. I'll look in to fixing this tomorrow.

**Comment by veiset** [comment]
I've updated the list of flask mods that came this league. Thanks for the report. Should be live in a few minutes
