### ISSUE TITLE
Map Modifier Regex for max res stoped working due to changes in wording

### ISSUE THREAD

**Issue by aeroncastle** [veiset/poe-vendor-string#136]
![image](https://github.com/veiset/poe-vendor-string/assets/2382737/3e0bfffa-b417-42e5-be7c-caf42ad76f20)

-#% maximum Player Resistances
changed to
Players have -% to all maximum resistances
so "!% ma" doesn't work for it anymore

**Comment by veiset** [comment]
Hey. This was fixed two weeks ago. You need to refresh the website.
