### ISSUE TITLE
"rmi"

### ISSUE THREAD

**Issue by ogurisan** [veiset/poe-vendor-string#137]
"rmi" 
mine throw speed have same regex as "harming "

17% increased Critical Strike Chance with One Handed Melee Weapons

**Comment by ogurisan** [comment]
mine thro speed is arming

**Comment by veiset** [comment]
Thanks for the report. I'll look in to this a bit later today.

**Comment by veiset** [comment]
I've changed a lot of things on how the regex generator for jewel works.

It should solve this issue and around 100 others. Let me know if you find any other inconsistencies.
