### ISSUE TITLE
Withered regex

### ISSUE THREAD

**Issue by sahsinevgen** [veiset/poe-vendor-string#142]
To find mod "Monsters deal #% extra Physical Damage as Chaos Monsters Inflict Withered for 2 seconds on Hit", as i see is enough 'ithe', now used 'withe'.
![image](https://github.com/veiset/poe-vendor-string/assets/53696342/8c64191b-e4b2-4dbb-a5be-3025174b7a88)

**Comment by veiset** [comment]
That'll match the magic maps with the following mod:

prefix: Sl**ithe**ring - Area is inhabited by Sea Witches and their Spawn
