### ISSUE TITLE
beast regex missing Black Mórrigan

### ISSUE THREAD

**Issue by Faldrim** [veiset/poe-vendor-string#152]
Not sure of any other missing ones

**Comment by DemonSkye** [comment]
+1

**Comment by SilverWF** [comment]
Same here - it is missing, while this is one of the most valuavble beasts atm

I suggest using "k mor" for it

**Comment by veiset** [comment]
Currently on vacation, I'll fix this when I get back from vacation early next week

**Comment by veiset** [comment]
Added this now. Thanks for the reports. Let me know if this doesnt resolve it.
