### ISSUE TITLE
Regex mixed up

### ISSUE THREAD

**Issue by Panix-Develop** [veiset/poe-vendor-string#153]
It seems that the Map Mods for "Players have #% less Cooldown Recovery Rate" and "Players have #% less Recovery Rate of Life and Energy Shield" are mixed up. I wondered why I bricked some maps because of the mixup until I tested it.

**Comment by veiset** [comment]
Hey, thanks for the report.

Do you have an example of a map where this is an issue? I can't reproduce it.

It looks like it works as intended for me:

Less recovery wont highlight:
![bilde](https://github.com/user-attachments/assets/f65b7af2-9086-4a9e-93d2-3e759461e91a)

Less cooldown wont highlight:
![bilde](https://github.com/user-attachments/assets/559808c0-e479-42aa-8117-1f669d8de22b)

**Comment by Panix-Develop** [comment]
Maybe I just made some mistakes with copying something... works for me, too after trying again. Sorry for the issue :-)
