### ISSUE TITLE
Regex overlap for steal charges (normal map) and impale mod for T17

### ISSUE THREAD

**Issue by ukeoinin** [veiset/poe-vendor-string#154]
Regex for _Monsters steal Power, Frenzy and Endurance charges on Hit_ `er,` will filter out the Impale mod due to the following _Monsters' Attacks Impale on Hit When a fifth Impale is inflicted on a Play`er,` Impales are removed to Reflect thier Physical Damage multiplied by their remaining Hits to that Player and their Allies within 1.8 metres_

**Comment by veiset** [comment]
This is now fixed. Thanks for the report.
