### ISSUE TITLE
Regex Filter Map Pack Size and Quantity is broken.

### ISSUE THREAD

**Issue by 8Times** [veiset/poe-vendor-string#155]
Pack Size of at least 25% will result in "iz.*([2-9].|1..)%".

All that filter does is to check if it is at least 20% and up to 199% which is not precise enough and irritating.

What I rather expect is something along this way: "iz.*(2[5-9]|[3-9].)%"

The "2[5-9]" signifies that it should be atleast 25-29% while "[3-9]." includes values from 30-99%. As of now there is no way to roll beyond 99% pack size and if the pack size chisel are being used the filter won't work anyway because of the second pack size line that will show up on the item.

As for Map Quantity I can't think of any nice solution that won't increase the length dramatically.

**Comment by veiset** [comment]
You can click the "optimize pack size value" if you want it to be more precise at the cost of query space:

![bilde](https://github.com/user-attachments/assets/627f1197-b1d5-4604-bab1-d21df2077042)

![bilde](https://github.com/user-attachments/assets/fa38878c-4e59-473d-b60a-3e16385b4cfb)
