### ISSUE TITLE
Regex for "Scarab of Divinity" is not matching

### ISSUE THREAD

**Issue by tmallwitz** [veiset/poe-vendor-string#161]
The Regex for "Scarab of Divinity" is "r," , but it does not match
The Current Text from c&p is:

Item Class: Map Fragments
Rarity: Normal
Scarab of Divinity
--------
Stack Size: 8/20
Limit: 2
--------
Up to 2 additional Rare Monsters in Area will be Pantheon-Touched
Apparitions spawned by Pantheon-Touched Monsters deal 100% increased damage
--------
Faith transforms.
--------
Can be used in a personal Map Device to add modifiers to a Map.

**Comment by veiset** [comment]
Thanks for the report. I've updated the scarab list, this should be fixed now!
