### ISSUE TITLE
Shorter Vendor Searches

### ISSUE THREAD

**Issue by Miku0Sama** [veiset/poe-vendor-string#166]
When looking for RGB sockets (for reselling for chromatics) you can use `:.*(?=\S*r)(?=\S*g)(?=\S*b)` instead as it uses fewer characters than what is currently given. (27 characters vs current 38)
AFAIK there is never a situation where an item will have the letters r, g, and b in a single word that is preceded by a colon in the same line. If there is you can always add `ts` at the start to guarantee that it will only check the sockets line of the item description which is still a fair bit shorter.

Additionally, when searching for x number of sockets (ignoring links) you can use `(\w\W){#}` where # is the number of sockets you want minus 1. This would only change the "Any 6 Sockets" option on the site for now.

Shortening these is nice since it allows you to find any reselling items with a single search rather than 2. Gotta farm those chromatics, jewellers and fusing orbs amirite?

Here is a picture from https://regexr.com showing a handful of tests for the RGB search with each being correctly identified. (And yes, I did test a few items in game as well and they worked as expected)
![image](https://github.com/user-attachments/assets/900e34dd-8725-4763-b0d8-ea67390c3ea6)

**Comment by veiset** [comment]
That's amazing. Can you do some testing ingame too? The Path of Exile regex engine has a lot of quirks, but I think this should work. 

If you can do just a quick test ingame for both cases I'll update the webpage, thanks!

**Comment by Miku0Sama** [comment]
I'm actually relatively new to the game so the items I have available to me are rather limited lol, but here are a couple screenshots of each one being tested with what I had available.

<details>
<summary>No Search</summary>

![image](https://github.com/user-attachments/assets/69c70de5-98a9-4876-b912-56f6b5d56142)
</details>
<details>
<summary>At least 5 sockets</summary>

![image](https://github.com/user-attachments/assets/896fa51c-3212-4014-aecf-b80a61a706ba)
</details>
<details>
<summary>At least 4 sockets</summary>

![image](https://github.com/user-attachments/assets/a37f8658-eaec-4da8-a837-6738c8a8d005)
</details>
<details>
<summary>Linked RGB</summary>

![image](https://github.com/user-attachments/assets/5f3d721c-3e40-4ea2-93cf-c39236ab623e)
</details>

**Comment by veiset** [comment]
Hey, this should be implemented now. Let me know if it isnt working correctly. Thanks for the suggestion.
