### ISSUE TITLE
beasts missing

### ISSUE THREAD

**Issue by Faimen** [veiset/poe-vendor-string#167]
some beasts like Black Morrigan and Sand Serpent are missing

**Comment by veiset** [comment]
Whats a Sand Serpent? 😁 

I can't find any info about it either on 
https://poe.ninja/economy/settlers/beasts
or on https://www.poewiki.net/wiki/Beastcrafting

Black Morrigan should show up

<img width="493" alt="image" src="https://github.com/user-attachments/assets/6f19409a-e6ec-4937-8bb4-937fcc7669d5">

**Comment by Faimen** [comment]
I think i confused you, and maybe this no longer a beast to catch

**Comment by veiset** [comment]
No worries, thanks for the report!
