### ISSUE TITLE
Map mod generator not working for #% Reduced Chance to Block

### ISSUE THREAD

**Issue by jvel14** [veiset/poe-vendor-string#168]
Generator outputs "!ur$" which does not catch this mod. "!d ch" is the correct string I believe.

**Comment by veiset** [comment]
Hey. Thanks for the report, I'll look in to this asap

**Comment by veiset** [comment]
This seems to work for me. Do you have some more details?

Example:

```
Item Class: Maps
Rarity: Rare
Unholy Oubliette
Necropolis Map
--------
Map Tier: 15
Item Quantity: +55% (augmented)
Item Rarity: +33% (augmented)
Monster Pack Size: +21% (augmented)
--------
Item Level: 83
--------
Monster Level: 82
--------
Area has increased monster variety
26% more Monster Life
Monsters fire 2 additional Projectiles
Monsters cannot be Stunned
Players have 30% less Armour
Players have 40% reduced Chance to Block
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
```

Matches `ur$` and get filtered by `!ur$`.

`#% Reduced Chance to Block` is a mod with two lines, both `Players have 30% less Armour` and `Players have 40% reduced Chance to Block`. 


Can you copy over the map that failed to match and give some more details please.
