### ISSUE TITLE
Map modifier regex and name regex overlapping each other

### ISSUE THREAD

**Issue by MartinDeluxe** [veiset/poe-vendor-string#172]
When you select you don't want to have "Monsters have 50% increased Accuracy Rating · Players have -20% to amount of Suppressed Spell Damage Prevented" on your map and you roll map named with "Revealed" in it, regex doesn't highlight map that meets the requirement.
![obraz_2024-10-02_190258854](https://github.com/user-attachments/assets/0b786f28-6244-4e17-af00-64daf01b812e)
![image](https://github.com/user-attachments/assets/4fb08fe7-9476-4419-9208-436cb5928c04)
![image](https://github.com/user-attachments/assets/75e4722b-8a15-4b15-9f6f-68bd7ee89d6f)

**Comment by veiset** [comment]
Hey, thanks for the detailed report and figuring out what the issue was. The webpage has been updated to fix this. It should be live in around 2 minutes
