### ISSUE TITLE
"ike" for increased Critical Strike Chance also marks reduced extra crit

### ISSUE THREAD

**Issue by verysecrethero** [veiset/poe-vendor-string#18]
hello, use "mult" instead of "ike" for increased Critical Strike Chance
since "ike" also marks reduced Extra Damage from Critical Strikes

**Comment by veiset** [comment]
It uses `ike ` (with the space), not `ike`, so `ike ` should not match `reduced Extra Damage from Critical Strikes`. 

Do you have an example of a map that falsly matches a query? I will look in to it and fix it if there is an issue. Could you please copy the text of the map (hoved it and click ctr+c) and the exact search query you used?

**Comment by veiset** [comment]
Thanks! I will look in to this later today!

**Comment by verysecrethero** [comment]
ok i had a hunch and i checked it, it only happens if you have "ike " in the end of the regex or just "ike "
if you try "ike |ail" then it will not mark the reduced crit ones
so what happens is probably that poe trims the end of the regex and gets rid of the extra space if you have "ike " in the end

**Comment by veiset** [comment]
Oh! Thanks for finding the issue. I'll update the generator this evening and update the page. I'll let you know when it's live

**Comment by veiset** [comment]
I had some time during lunch. It should be resolved now 😁 Can you verify it solves the problem? poe.re is updated with the new regex

**Comment by verysecrethero** [comment]
hello, nice! good idea to make it "ke c" instead and i see you changed 2 other things as well
ive tested it and the new regex seems to work fine now
good job, thanks for the update and the tool is very nice and useful

**Comment by veiset** [comment]
Great! Thanks for taking the time to do some digging.

I got a tool that automatically generates the regexes, which also does a lot of checks to hopefully ensure the results are correct, but in this case the regex in game was acting weirdly with the trim logic. 

Just as a bonus fun fact: `mult` would have matched magic maps with the modifier `Area has increased monster variety`, since the modifier is named `Multifarious` 😅
