### ISSUE TITLE
Feature suggestion : match # of linked R, G, B instead of using a strict order.

### ISSUE THREAD

**Issue by TheZeal** [veiset/poe-vendor-string#25]
`ts:.+(?=(\S*r){X})(?=(\S*g){Y})(\S*b){Z}`

This regex searches for X+ red sockets, Y+ green sockets, Z+ blue sockets that are in the same link group. This is useful for 4L+ searches.

Quick explanation : 
`ts:.+` => to select the `Sockets: ` line
`(?=(\S*r){X})` => lookahead of X r sockets that are connected together, stops on seeing a space
`(?=(\S*g){Y})` => lookahead of Y g sockets that are connected together, stops on seeing a space (so guaranteed both lookaheads are in the same group)
`(\S*b){Z}` => no lookahead required here because it's the last request. 

Can remove any () block that has 0 matches requested and keep the last one without any lookahead for shorter regex. Example : if someone wants 2r and 1g linked together, you can do `ts:.+(?=(\S*r){2})(\S*g){1}`

Also, your 3L string could be shorter by 3 chars with `-\w-`
Your 4L string could be `-\w-.-`
And you could add 5L/6L with `(-\w){4}` and `(-\w){5}`.

**Comment by veiset** [comment]
This is really great stuff. I'm not sure I have time to implement this before the league start, but the 4L+ regex is very clever and usefull for sure! 

I will implement this when I get time!

**Comment by veiset** [comment]
Solved by @Aneduna in #28
