### ISSUE TITLE
Missing modifiers for map rolling, increased number of rare monsters etc

### ISSUE THREAD

**Issue by MvPGEO** [veiset/poe-vendor-string#33]

**Comment by veiset** [comment]
hey, do you have an example of a map where this is an issue?

(ctrl+shift+c)

**Comment by MarombeiroT** [comment]
2 maps, 1 with more magic and 1 with more rare

Item Class: Maps
Rarity: Rare
Dire View
Spider Forest Map
--------
Map Tier: 16
Item Quantity: +82% (augmented)
Item Rarity: +37% (augmented)
Monster Pack Size: +24% (augmented)
Quality: +20% (augmented)
--------
Item Level: 83
--------
Area is inhabited by 2 additional Rogue Exiles
21% more Magic Monsters
23% increased Monster Damage
Monsters take 38% reduced Extra Damage from Critical Strikes
+25% Monster Chaos Resistance
+40% Monster Elemental Resistance
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
----------------------------------
 

Item Class: Maps
Rarity: Rare
Fungus Trap
Spider Forest Map
--------
Map Tier: 16
Item Quantity: +81% (augmented)
Item Rarity: +36% (augmented)
Monster Pack Size: +23% (augmented)
Quality: +20% (augmented)
--------
Item Level: 84
--------
24% increased number of Rare Monsters
Monsters have 100% increased Area of Effect
Area contains two Unique Bosses
Players have 60% less Recovery Rate of Life and Energy Shield
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

**Comment by RickTorresJr** [comment]
Also missing: `Monsters Cannot Be Affected By Elemental Ailments` (rolled it on a T16)

![image](https://user-images.githubusercontent.com/12430441/192334349-050d6992-6816-49c4-b842-6b2d943c5d5c.png)

**Comment by veiset** [comment]
Hey, sorry about this taking some time, I will try to make some time this weekend. Pretty busy IRL at the moment.

I think the `Monsters Cannot Be Affected By Elemental Ailments` modifier is actually `Monsters have 70% chance to Avoid Elemental Ailments`, but gets renamed when map/atlas modifier makes it go over 100%. 

You should be able to avoid rolling this modifier by selecting `Monsters have X% chance to Avoid Elemental Ailments`. 

Is somebody able to verify the ailment modifier? Either check that my theory holds up or give me an example of a map that has it rolled before placed in to the map device?

**Comment by RickTorresJr** [comment]
You're right. Just confirmed. Thanks for the quick reply.

![image](https://user-images.githubusercontent.com/12430441/192545502-75c0789d-267b-443f-b473-167e0dd371b8.png)

![image](https://user-images.githubusercontent.com/12430441/192545567-d9cd761d-9302-40d1-b3ea-a8fa5ce72f37.png)

**Comment by veiset** [comment]
This should be fixed in https://github.com/veiset/poe-vendor-string/issues/33

Its live on with the new modifiers, please try it out: https://poe.re/#/maps

**A bit of what happened:**
The modifiers with nemesis/bloodlines was renamed/reworked to only increase monster pack size, and the part of poe.re that handles that didn't account for that change. I've fixed that and it should now work.

Thanks for reporting this issue and giving details @MvPGEO / @MarombeiroT
