### ISSUE TITLE
Feature Suggestion : Scepter

### ISSUE THREAD

**Issue by beaniesbroyt** [veiset/poe-vendor-string#34]
Scepter leap slam leveling is currently meta for a lot of builds, and adding even just "scept" to the regex site would make it much more convenient than having to add it manually.

**Comment by veiset** [comment]
I'll see if I can a category for weapon types. I don't see this being used too much, but if there is a need for it I will add it.

Is there a need for different weapon-bases or is just the base-type enough?

**Comment by beaniesbroyt** [comment]
Short answer is yes just scepter is enough, long answer is having all of them would help future proof it. 

An example in 3.19 would be swords being great for helix in act 1 but axes completely overtake them at poleaxe but act 1 is really the most imortant regex the rest depends on RNG I might check the vendor but ideally I won't at all after merveil.
Helix likely isn't going to be used for leveling but i'm sure similar situations will be present in whatever the future meta replacement is. 

The reason I add "scept" is because the vendor greying out the scepters makes it hard to see them so i'd have to clear the search field after searching for 3 links then check them if I did not add that line. It sounds ridiculous but every few seconds in town when speed running matters. 

I do acknowledge that the amount of people that benefit from this will be low so I appreciate your time wether it gets implemented or not 🤟

**Comment by veiset** [comment]
Yep. Thats a really good point, the only drawback of selecting "Scepter" for instance is that the socket links/colors will be harder to spot, as all the scepters will be highlighted. But I do see the need for this, you most likely want your socket links on other gear in any case.

I will see if I have time to add this this evening (in around 10 hours). I will add a warning about it will highlight all of the item basetypes you select and colors not being highlighted (as everything is highlighted).

**Comment by veiset** [comment]
![image](https://user-images.githubusercontent.com/329529/205692510-084edd9a-0024-4616-9038-046aa7a02368.png)

Currently working on it. It will be ready pretty soon. One thing I am unsure about is the ordering of the items.

I am thinking maybe

```
Axe, Mace, Sword
Sceptre, Wand, Staff
Bow, Claw, Dagger
```

Any thoughts?
