### ISSUE TITLE
Gwennen Regex Rolling

### ISSUE THREAD

**Issue by veiset** [veiset/poe-vendor-string#36]
Since xanthics will stop maintaining the gwennen rolling it would be nice that it's a part of poe.re

> Of which, I am looking for someone to take over/replace https://github.com/xanthics/poe_gen_gwennen. ;) I'm taking a longish break from poe and would be better, for me, if someone else maintained a similar tool.

- [xanthics](https://www.reddit.com/user/xanthics/)

**Idea how to solve the economy part:**

Use the poe.ninja API to look up prices during the build step to generate an economy json file. Use this json file as a base for figuring out which items to display by default and the relative value of items. Then trigger the build automatically every hour or so with github actions. Use a banlist of items that cannot found from gwennen.

This would make it relatively low maintenance while also tracking the economy. 

**Resources:**

https://github.com/xanthics/poe_gen_gwennen/blob/master/ninja_data.py

https://poe.ninja/api/data/itemoverview?league=Kalandra&type=UniqueWeapon

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by veiset** [comment]
@xanthics this should be ready for use now. I will still polish the next week before the league launches. The economy is automatically updating with some fallback economy files in case the league isnt found or doesn't have any economy data. 

You can check it out at https://poe.re/#/expedition

**Comment by xanthics** [comment]
> You can check it out at https://poe.re/#/expedition

Looks good.  I'll replace my root page with a link to yours in a week or so.

**Comment by veiset** [comment]
This is now implemented and live 🎉 🎉
