### ISSUE TITLE
map mod bug

### ISSUE THREAD

**Issue by Slevin3k** [veiset/poe-vendor-string#37]
Selecting "I don't want any of these mods" and:

Players cannot Regenerate Life, Mana or Energy Shield
-X% maximum Player Resistances
Players have X% reduced effect of Non-Curse Auras from Skills
Players have X% reduced Chance to Block Players have X% less Armour
Players have X% less Cooldown Recovery Rate

will generate:

"!ege|tances|non|loc|coo"

The 'tances' part will exclude "+X% Monster Chaos Resistance +X% Monster Elemental Resistance" which isn't supposed to be excluded.

**Comment by veiset** [comment]
Thanks. Looking in to this!

**Comment by veiset** [comment]
Same issue as https://github.com/veiset/poe-vendor-string/issues/38

I am updating the status at that issue.e
