### ISSUE TITLE
Map mods - Regex bug

### ISSUE THREAD

**Issue by Jasper-Mui** [veiset/poe-vendor-string#38]
Description:
![image](https://user-images.githubusercontent.com/58538645/207467252-1acd2419-908d-4c5e-bff3-8f763085f2f1.png)

I am using. 
using "!ege|s rec|tances|h el|tal d|elo|h tem|coo"

List of mods "I have as don't want any of these mods"
Monsters reflect X% of Elemental Damage
Players cannot Regenerate Life, Mana or Energy Shield
Players are Cursed with Temporal Chains
-X% maximum Player Resistances
Players have X% less Recovery Rate of Life and Energy Shield
Monsters' Action Speed cannot be modified to below base value Monsters cannot be Taunted
Players have X% less Cooldown Recovery Rate
Players are Cursed with Elemental Weakness
Players are Cursed with Elemental Weakness

Problem: 
The "tal d" and "tances" in the regex is to generic. 
For when the map mod contains "Monster elemental resistances"

**Comment by veiset** [comment]
Thank you. I will look in to this tomorrow. Hopefully I will have a fix in around 15 hours.

**Comment by veiset** [comment]
I found the issue. The modifier "+% monster elemental resistance**s**" has been renamed from "+% monster elemental resistance". I have a fix on it, but unable to test it at the moment. I will have to do some testing after work, so expect a fix to be live in around 5 hours. 😄

**Comment by veiset** [comment]
Fixed with badf1239 - the update is live on the webpage. Thanks for the bug report and let me know if you find any other issues.
