### ISSUE TITLE
Armour Mod breaks Map string

### ISSUE THREAD

**Issue by Mongrul** [veiset/poe-vendor-string#43]
**Players have X% reduced Chance to Block Players have X% less Armour**

This seems to break the string whenever I have this selected in the Map modifiers

**Comment by veiset** [comment]
![image](https://user-images.githubusercontent.com/329529/210258792-48c90611-2660-4512-98b0-ebffc92ee99a.png)
![image](https://user-images.githubusercontent.com/329529/210258820-90378bd9-c0f2-4bcb-a704-90ce92766adb.png)


I am not able to reproduce this, are you able to give me some more information? 

Also in which way does the it break?

**Comment by Mongrul** [comment]
Strange it is working now.  For testing this is the one I am using.  

"!% ma|s rec|non|as c|as l|tun|elo|ege|r el|loc"
