### ISSUE TITLE
Need to show full regex for those without a pc

### ISSUE THREAD

**Issue by demonblaze0** [veiset/poe-vendor-string#48]
Those of of us without a pc (ie using a mobile device) can’t copy paste in game so it would be helpful to see the full regex to copy by eye

**Comment by veiset** [comment]
Thanks for the report. I will try to have a fix on this as soon as I find time!

**Comment by veiset** [comment]
Fixed by @draperunner in https://github.com/veiset/poe-vendor-string/pull/96
