### ISSUE TITLE
[Feature] Auto Detect from Existing Regex

### ISSUE THREAD

**Issue by ripslayer** [veiset/poe-vendor-string#5]
As the title says. I have already got a Regex from the site so if I want to further modify the regex like removing something or adding more to it. I will simply paste the original one and it will update the checkbox according to my regex and keep on modifying instead of choosing everything from the start as usual. 

Maybe it sounds like I'm lazy lol

Thanks for this site tho.

**Comment by veiset** [comment]
Oh, thats a very good feature to be honest! 

It requires quite some work because how the shortening works, but I'll see if I can figure out something.

**Comment by veiset** [comment]
The search query is now presistent. So even if you refresh the page or come back later the **last** query should be stored.

Does this solve the issue? Or is this a use case where you want to have different strings for different builds and able to quickly edit them on the webpage?
