### ISSUE TITLE
Feature Suggestion: Split line into multiple lines if character count is > 50

### ISSUE THREAD

**Issue by cdrg** [veiset/poe-vendor-string#54]
Xanthic's tool did this

**Comment by veiset** [comment]
I will implement this if more people request it. For now you can select all the items you want and split it somewhere in the middle (just split it at a `|` and make it in to two lines for the macro). Even though you get a warning atm it still will output the whole selected regex.

**Comment by cdrg** [comment]
> I will implement this if more people request it. For now you can select all the items you want and split it somewhere in the middle (just split it at a `|` and make it in to two lines for the macro). Even though you get a warning atm it still will output the whole selected regex.

BTW, this is not true. It displays "..." and cuts the string off.
