### ISSUE TITLE
"cannot regen" regex shortens to "ege", which also includes Siege map. 

### ISSUE THREAD

**Issue by ThirteenEra** [veiset/poe-vendor-string#55]
As title says, "ege" which is shorthand regex for "cannot regen" also will always select Siege map, since it contains same letters.

**Comment by veiset** [comment]
Thanks for the report, I will have a look at this a bit later today! I know the issue, and I hope to fix this in a few hours.

**Comment by veiset** [comment]
This should be now be fixed. The reason for this bug was that some old maps were reintroduced in to the atlas. I will find a better solution to handle this next league, for now I just regenerated the regex with all the maps.
