### ISSUE TITLE
Elderslayers invitation is not highlighted

### ISSUE THREAD

**Issue by BD9a** [veiset/poe-vendor-string#57]
**Maven's Invitation: The Elderslayers** is not highlighted when You want to avoid **Monsters have a #% chance to avoid Poison, Impale, and Bleeding** modifier because **n,** regex is matching Al-Hezmi**n,** The Hunter in item description.

**Comment by veiset** [comment]
The fix should be live in around 5 minutes. Thanks for reporting it, and let me know if you find something else thats not working correctly.
