### ISSUE TITLE
[Feature] Remember previously selected mods

### ISSUE THREAD

**Issue by willlowther** [veiset/poe-vendor-string#6]
I love the tool and keep it pinned as a tab, but it doesn't "remember" which mods I've previously selected to generate the strings between reboots. It'd be great if there was a cache/cookie that stored the last-used string upon re-loading the page.

**Comment by veiset** [comment]
Thanks for the feature request. Thats a very good idea!

This should now be live on the webpage! 😁 

I've also added a reset-button to the vendor search selection as well, since refreshing no longer clears the search.
