### ISSUE TITLE
Bestiary regex

### ISSUE THREAD

**Issue by Tadiian** [veiset/poe-vendor-string#64]
Would it be possible to add regex filter to the side to filter valuable beasts?  
Not sure how to add a tag for "enhancement"?

**Comment by veiset** [comment]
Is the use case for this just for getting the most valuable beasts, or also specific ones? 

Note to self, poe.ninja API:
https://poe.ninja/api/data/itemoverview?league=Crucible&type=Beast&language=en

**Comment by Tadiian** [comment]
For me personally it would be fine to have the most expensive ones, not sure if there are any other uses it could have anyway but there probably is something for someone? :)

**Comment by veiset** [comment]
A early preview is ready on https://poe.re/#/beast

Let me know if it works, or if any beasts are missing/extra beasts are showing up.

It was a bit tricky to solve this because of all the rare monster names that can match.

**Comment by veiset** [comment]
This should be live in a few minutes!
