### ISSUE TITLE
Consider multiple mods with same substrings and consolidate accordingly

### ISSUE THREAD

**Issue by Hexogenx** [veiset/poe-vendor-string#66]
Example:
I want to filter for all maps that have no extra phys as cold, no extra phys as fire, no extra phys as chaos, no extra phys as lightning.
Currently, when selecting these, the generated string is "!withe|as co| as f|as l" (25 characters long).
All of these mods contain the substring "deal #% extra Physical Damage as", so "!% e" (6 characters long) is a way better substring to filter for, since it is also exclusive to these 4 mods.
I'm not a programmer, but briefly checking the code, it seems that instead of calculating the best substrings for a set of mods algorithmically, the regex for a specific mod is just hardcoded and concatenated?
There is a similar project by xanthics that uses lists of ngrams instead of single hardcoded mod substrings and then selects from them, prioritizing the shortest repeating ngrams for a set of mods. This would massively increase the efficiency of the filters and negate in part the 50 character limitation imposed by GGG.

**Comment by veiset** [comment]
Good suggestion, but that requires a lot of work.

> I'm not a programmer, but briefly checking the code, it seems that instead of calculating the best substrings for a set of mods algorithmically, the regex for a specific mod is just hardcoded and concatenated?

Running the ngram algorithm in frontend dynamically would make the page really slow as the generator currently uses around 15000 inputs to create the pre-generated static file you found (using ngrams to figure out the shortest unique mod), but exposing some of the ngrams for each mod and doing some work at the frontend side of things should be possible (but a bit tricky). 

I will probably not implement this right away, as there are a lot of other tasks in the backlog and this is a bit of an undertaking to do. But I will probably look in to improving this at a later stage.

**Comment by veiset** [comment]
Implemented.
