### ISSUE TITLE
Copy/Paste function issue

### ISSUE THREAD

**Issue by SpreadYourButter** [veiset/poe-vendor-string#67]
When I hit the green "Copy" button, I can paste the regex into the poe search bar and everything works fine.  If I copy the regex into a Discord PM, some of the font gets all awkward and it doesn't work properly (the map seller gets no results, i also get no results when i copy it from Discord). Any solutions for this?

to clarify, this is for the map modifier tool

**Comment by SpreadYourButter** [comment]
ok ive figured it out. the *'s change the font in discord to italicized and get rid of them altogether. now to figure out how to do a search without them

**Comment by SpreadYourButter** [comment]
for anyone else having this issue when searching for maps:
if your regex has 2 asterisks (*), add a backspace (\) before and after the asterisks.

example:
"!gen" "m q.\(\d[3-9]\d)" "iz.*([3-9]\d|\d{3})"   <<< this is the copy/paste from the website. it wont work in discord DMs
"!gen" "m q.\*(\d[3-9]\d)" "iz.*\([3-9]\d|\d{3})"  << add two \ to tell discord to ignore formatting options.

man poe makes me feel fucking stupid. i hate this game.

**Comment by veiset** [comment]
Hey. To fix the formating on discord you can make it a code-block formatted string by using backticks around the string (`).

Example:

```
`"!gen" "m q.(\d{3})" "iz.([3-9]\d|\d{3})"` 
```

**Comment by SpreadYourButter** [comment]
> Hey. To fix the formating on discord you can make it a code-block formatted string by using backticks around the string (`).
> 
> Example:
> 
> ```
> `"!gen" "m q.(\d{3})" "iz.([3-9]\d|\d{3})"` 
> ```

well thats way easier. thanks.
