### ISSUE TITLE
Regex for map quant between 101-109 incorrect

### ISSUE THREAD

**Issue by totalnewbie99** [veiset/poe-vendor-string#71]
When entering a value for map quant between 101 and 109, the generated regex is, for example:
"m q.*(\d0[5-9]\d|\d[1-9]\d)"

The first half is supposed to capture 105-109 but there's an extra \d after the [5-9] so it's actually looking for a 4 digit number and thus doesn't match correctly.

**Comment by veiset** [comment]
Hey, thanks. This should be fixed now.
