### ISSUE TITLE
Flask Regex: Surgeon's regex "eo" matches leech description

### ISSUE THREAD

**Issue by cblack-f3** [veiset/poe-vendor-string#72]
**Flasks Regex**
`eo` intended to match `Surgeon's` also matches the description of Leech Suffix (word: `Simultaneously`)

**Comment by veiset** [comment]
It doesn't seem like the regex is matching description texts.

![image](https://github.com/veiset/poe-vendor-string/assets/329529/bcf64a9d-7c42-4d34-bd2b-0fd8f0585012)


It might be something else that wasn't correct. If you find the same bug again, can you copy the flasks you expected to match and the flasks that got matched?
