### ISSUE TITLE
Improved map quant regexes

### ISSUE THREAD

**Issue by rmelcer** [veiset/poe-vendor-string#77]
Hey, thanks for the awesome tool. I think I've found some opportunities to reduce the character counts of quantity regexes. I've numbered the suggestions below to make them easier to reference. All of these changes are compatible with each other, and (3) and (4) could be implemented independently of (1) or (2).

1. Replace `\d` with `.` by ending the regex with `%`. The percent will guarantee that we won't pick up any non-number strings by substituting to `.`.
```
Current 80%: "m q.*([89]\d|\d{3})"
New 80% saves 3 chars: "m q.*([89]|1.).%"
Current 75%: "m q.*(7[5-9]|[89]\d|\d{3})"
New 75% saves 2 chars: "m q.*(7[5-9]|[89].|1..)%" - one less saved character because we had to move the last digit inside the match.
Current 107%: "m q.*(\d0[7-9]|\d[1-9].)%"
New 107% is net neutral: "m q.*(\d0[7-9]|\d[1-9].)%"
Current 113%: "m q.*(1[1-9][3-9]|1[2-9]\d)"
New 113% is net neutral: "m q.*(1[1-9][3-9]|1[2-9].)%" - though this could be optimized to use [^0] instead of [1-9] to save one character
```
2. Remove the beginning `m` - by adding %, we already guarantee that the only line that can match is item quantity (note we still need the space), which saves 1 character for every value.
```
Updated 60%: "m q.*([6-9]\d|\d{3})"
Modified 60% using (1) above: "m q.*(6[89]|[7-9].|1..)%"
New 60%: " q.*(6[89]|[7-9].|1..)%"
```
3. For 100+ quants, move the 1 outside of the matching group - this change is independent of the others.
```
Current 103%: "m q.*(\d0[3-9]|\d[1-9]\d)"
(3) only saves 2 characters: "m q.*1(0[3-9]|[1-9]\d)"
(1), (2), (3) combination saves 3 characters: " q.*1(0[3-9]|[1-9].)%"
```
4. Remove the match group from 100,110,120 - especially useful when selecting "Optimize Quantity Value". This change is independent of the others).
```
Current 110%: "m q.*(\d[1-9]\d)"
(4) only saves 2 characters: "m q.*\d[1-9]\d"
(1), (2), (3), (4) combination saves 4 characters: " q.*1[1-9].%"
```
5. Use ^0 instead of 1-9. Requires (1) - since we have an ending `%`, we already know this will only match the numbers in the quant mod, and [^0] saves one character over [1-9]
```
(1) only 116%: "m q.*(1[1-9][6-9]|1[2-9].)%"
(1) & (5) saves 1 character: "m q.*(1[^0][6-9]|1[2-9].)%"
(1), (2), (3), and (5) saves 3 characters: " q.*1([^0][6-9]|[2-9].)%"
```

I think all of these are transferable to pack size as well - with the leading `i` being equivalent for (2).

I don't have a good way to test this with all possible map enchantments, special implicit modifiers, delirious modifiers, but I haven't been able to break it yet.

**Comment by rmelcer** [comment]
For an idea of typical savings with all changes:
* 70/80/90/100% saves 4 characters
* 75/85/95/105% saves 3/3/2/4 characters

**Comment by veiset** [comment]
This is awesome! A lot of good suggestions and improvements here. I am out traveling, heading to asia and exilecon, but I will try to find time to fix this before next league.

If you want you can open a PR for it, the code that deals with the number to regex logic can be found here:
https://github.com/veiset/poe-vendor-string/blob/master/src/utils/MapOutput.ts#L69C9-L69C9

**Comment by veiset** [comment]
Currently working on this atm. Very good info, only thing that didn't work to shorten was "m q.*" to " q.*", as the ingame client strips spaces in expressions, even when quoted. I need to do some more testing, but I think I will be able to publish this later today.

Thank you so much for the detailed shortenings with examples and all!

**Comment by veiset** [comment]
It's live. Let me know if you have any more ideas about optimizing the lengths!
