### ISSUE TITLE
Flask regex needs tweaking (again)

### ISSUE THREAD

**Issue by Meisen1977** [veiset/poe-vendor-string#78]
Hi there, i'm back to complain about flask regex :D

I wanted to roll increased duration on some quicksilver flasks for leveling, so your website spat out "xp|cli|xa|anal|inv"

The issue is that "cli" (Cinician's) gets triggered by the "Right CLIck to drink" text you find on all flasks... :(

EDIT:

I found another small thing. Not sure if this "needs" to be fixed or if you find it too niche to worry about... anyways;

If you want to highlight any tier of the suffix that gives you corrupted blood/bleed immunity your website spits out "af", which is an amazing shortcut to include a lot of suffixes, but... that also highlights any and all flasks that you have a bench craft on because of the text "Master CrAFted Suffix Modifier".

Now, this is kind of nitpicky as you can't roll the bleed immunity on utility flasks, and i'd argue you're very unlikely to bench craft non utility flasks, so when rolling flasks, this is not an issue, and when searching your tab for flasks, i'd argue it's very easy to quickly see the difference between a life flask and an utility flask... So, the question becomes, is it worth losing 1 space in the regex changing "af" to "aff" for the benefit of not highlighting flask you have bench crafted in your inventory whilst looking for life flasks with the bleed immunity suffix? Idk... I'll leave the decision up to you :)

Actually... as i wrote this i remembered that, at least for me, my regex's for utility flasks are usually very long and often leave out something i might've wanted to include, cause there's just not room... My regex for rolling life flasks on the other hand is short and does not struggle with the 50 char limit at all, not even close, and as such, even though the upside is (arguably) a bit ocd-ish, i do not see a real world issue with changing "af" to "aff" :)

**Comment by veiset** [comment]
Thanks, for the report! This is some great info, I'm out traveling atm but I'll try to find time to fix this asap.

**Comment by veiset** [comment]
Thanks! So I reran the regex generator with the two new tokens ("Right Click to drink", and "Master crafted Suffix Modifier").


```
-   regex: "xp|cli|xa|anal|inv",
+   regex: "xp|clin|xa|anal|inv",

      name: "Clinician's",
      value: "(31-35)% increased Duration",
-     regex: "cli"
+     regex: "clin"

      name: "Masochist's",
      value: "Gain 2 Charges when you are Hit by an Enemy",
-     regex: "mas"
+     regex: "aso"

      name: "of Draining",
      value: "0.8% of Spell Damage Leeched as Energy Shield during Effect",
-     regex: "dr"
+     regex: "dra"

    description: "Grants Immunity to Bleeding for # seconds if used while Bleeding Grants Immunity to Corrupted Blood for # seconds if used while affected by Corrupted Blood",
-   regex: "af",
+   regex: "aff",

      name: "of the Skink",
      value: "Immunity to Bleeding and Corrupted Blood during Effect (44-40)% less Duration",
-     regex: "ink"
+     regex: "skin"
```

Currently on mobile data so I can't push the fix. But I will push this when I get WIFI.

**Comment by veiset** [comment]
Alright.  This should be live now. And thanks for the report! Please let me know (again) if you find something else, really appreciate the bug reports! 😁
