### ISSUE TITLE
Expedition/Gwennen Regex Strings Match Item Implicits in Gambling Window (again)

### ISSUE THREAD

**Issue by halfacandan** [veiset/poe-vendor-string#80]
Hi

As a follow-up to #79, some of the regex strings in the [src/generated/GeneratedExpedition.ts](https://github.com/veiset/poe-vendor-string/blob/master/src/generated/GeneratedExpedition.ts) file are still incorrectly matching implicit modifiers of other base items. Thought it best to open a fresh issue since the previous one is closed.

I have listed these unintended matches below and proposed new regex strings to avoid the issues.

Many Thanks
Dan

| Item                  | Current | Proposed | False Positive Implicit                       | Example Item             |
| --------------------- | ------- | -------- | --------------------------------------------- | ------------------------ |
| stiletto              | til     | stil     | increased Projec**til**e Speed                    | Feathered Arrow Quiver   |
| supreme spiked shield | up      | upr      | chance to S**up**press Spell Damage               | Ornate Spiked Shield     |
| widowsilk robe        | ws      | wsi      | increased Critical Strike Chance with Bo**ws**    | Spike-Point Arrow Quiver |

**Comment by veiset** [comment]
Thanks. I will look in to this, this is probably due to my base item list being incomplete!

**Comment by veiset** [comment]
Ah, I found the issue. I was only using weapon bases, not all items. 

I need to find a list of all implicit modifiers items can have before fixing this, I will take a look and see what I can find. I probably wont have this done before after Exilecon though.

**Comment by halfacandan** [comment]
No worries. Thanks for taking a look at this 👍

**Comment by veiset** [comment]
Alright this should be fixed and live now. Thanks for reporting this, appreciate the help! 

Not too happy with the current fix, I need to figure out a good source for all item implicits at some point. But thats work for later :D

**Comment by halfacandan** [comment]
Looks great! I see you found a couple more mismatches that I hadn't. Thanks again for all your work on this: I know bugfix isn't the fun part :D

**Comment by veiset** [comment]
I don't mind fixing bugs at all. I'm just grateful people actually report bugs 😁

The worst are bugs I don't know about, so again thanks for reporting them!
