### ISSUE TITLE
Feature suggestion: ele dot multi vendor search options

### ISSUE THREAD

**Issue by mrooney** [veiset/poe-vendor-string#81]
At ilvl 4, vendors can sell wands with 14-18% cold/fire/chaos multi. It would be awesome to have 3 boxes for these as they can be almost as good as a link or gem level. Suffixes are Inclement | Earnest | Waning respectively for ilvl 4.

It's possible they could even replace the flat dmg to spells box, since those are implicits now and will match almost anything :(

**Comment by veiset** [comment]
That's a great suggestion, I'll add it ASAP.

**Comment by veiset** [comment]
Alright. Its updated and live on the webpage, thanks for the suggestion @mrooney. It's not optimized at the moment, but I will look in to that later.

**Comment by veiset** [comment]
If you can figure out safe shorter matches for `Inclement | Earnest | Waning` I'll happily update the regex, currently out traveling so I don't have time to do that at the moment. It will probably be after league launch that I get time to get a good system to figure the shortest.

**Comment by mrooney** [comment]
Wow, quick work, thanks! Can't wait to use this for 3.22 :) I made a quick PR at #82 as the fire/cold got swapped, and I also did my best to shorten them. If there's a better way let me know!

**Comment by veiset** [comment]
> Wow, quick work
> fire/cold got swapped,

Someone would even say a little too quick 😂 

Thanks for the PR, really appreciate it. Merged and deployed to the webpage!
