### ISSUE TITLE
Future Suggestion: 3 socket with at least the specified colors

### ISSUE THREAD

**Issue by Rax246** [veiset/poe-vendor-string#83]
e.g. any 3 socket with at least 2G (link agnostic)

**Comment by ar1a** [comment]
isn't that just this?
![image](https://github.com/veiset/poe-vendor-string/assets/8436007/6158b76f-3a47-433f-8e80-9f074d96f24f)

`g-g-|-g-g|g-.-g`

**Comment by Rax246** [comment]
3 socket. Not necessarily 3 link.

**Comment by veiset** [comment]
Hey. Thanks for the suggestion, but it's a bit niche. I will implement it if it gets requests again.

**Comment by Rax246** [comment]
Ok, thanks for the consideration!
