### ISSUE TITLE
Add max level requirement for beast regex

### ISSUE THREAD

**Issue by marensdorf** [veiset/poe-vendor-string#84]
A common farming strategy for beasts is running low-tier maps, but the regex quickly fills up with high-level requirement beasts that can't be found in that tier of maps. Would be great if we could filter those other beasts out (though have been only able to find [an old data-mined source](https://www.reddit.com/r/pathofexile/comments/859itk/datamined_list_of_legendary_beast_spawn/) for drop level).

**Comment by veiset** [comment]
That's a good suggestion. So the use-case is to cap it by drop level of the beasts? I'm a bit unsure if I'm comfortable making it an input field without a lot of testing.

Would it help if I added a column with the item level in the table and made it possible to toggle them from the table?
