### ISSUE TITLE
Beastiary Filter not working - hiding fenumal plagued arachnids

### ISSUE THREAD

**Issue by wentsouth** [veiset/poe-vendor-string#85]
The filter for fenumal plagued arachnids shows them as high value price (listed at 45c atm) but does not highlight them with the search string generated. They are shown as grey on the site aswell. 

Edit: After looking down the list other high value beasts also dont show up but are listed with high price. Might be due to max string length. A Warning on top of the site might help players see that they have high value beasts before deleting.

**Comment by veiset** [comment]
There was some weird stuff going on (I blame javascript!), it should be fixed now. The highest valued beats should be sorted correctly.

Thanks for the report!
