### ISSUE TITLE
hi how can i translate it into chinese？

### ISSUE THREAD

**Issue by gstarwd** [veiset/poe-vendor-string#87]
where should i start？
in which resouce should I  translate?

**Comment by veiset** [comment]
Hey. Thanks for the interest. I haven't thought about multi language support yet, but it's definitely something I want to add support for.

Do the regexes work in-game with the current generated regex? Or do the regex need to be localized aswell?

Translating the webpage is one thing, but it will be very hard to add support for multi language regex.

**Comment by gstarwd** [comment]
current reg is not work,  i think maybe it is more easy to use is to add english  text patch in  in  local game? in this way your tool will be worikng i think

**Comment by veiset** [comment]
Thanks. You're right @gstarwd, if you're able to add English to the game the webpage should work. I won't be able to make chinese regex I'm afraid, so this translation job is quite big. I might look into it later, but for now I'll close this issue as wont fix.
