### ISSUE TITLE
Suggestion/optimisation: dual reflect

### ISSUE THREAD

**Issue by Readie** [veiset/poe-vendor-string#88]
For the map regex generator, selecting both physical and elemental reflection generates the following 10-character pattern:

`"f ph|tal d"`

However this is unnecessary. The string "ref" appears *only* in the two reflect mods, and no map name contains the string either, so the generated pattern could be reduced down to just those 3 characters if someone chooses to include both physical and elemental reflection in their final pattern.

**Comment by gstarwd** [comment]
您好 您的邮件我已经收到~
----
王迪

**Comment by Meisen1977** [comment]
Ohhh... If you're able to do these kind of optimizations, i feel like i need to mention this one; (It's already been mentioned before, but i can't seem to find it right now, so i'll just add it here :))

Monsters deal #% extra Physical Damage as Chaos Monsters Inflict Withered for 2 seconds on Hit
Monsters deal #% extra Physical Damage as Cold
Monsters deal #% extra Physical Damage as Fire
Monsters deal #% extra Physical Damage as Lightning

If you want to block all these, and it's not unlikely that ppl would want to, then your site spits out "!withe|as co| as f|as l"
This, amazingly enough, can be reduced to "!% e" Saving "half a regex" :D It only works if you want to block all four ofc, but if you are in that scenario, it's a godsend <3

**Comment by veiset** [comment]
Fixed
