### ISSUE TITLE
beast regex should have a option to ignore all harvest beast

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [veiset/poe-vendor-string#89]
I guess most of player only do normal beast farm?

**Comment by veiset** [comment]
![image](https://github.com/veiset/poe-vendor-string/assets/329529/a80a3d8f-912a-47bb-8573-60e262ea851f)

List of harvest beasts!

I'll add a checkbox to enable/disable these mobs from the regex

**Comment by veiset** [comment]
It should be live in a few minutes. Thanks for the suggestion.
