### ISSUE TITLE
[Bug] Clash with "Action speed cannot be modified" and blighted maps 

### ISSUE THREAD

**Issue by chhallchase** [veiset/poe-vendor-string#9]
The regex that you generate when selected either not or include action speed cannot be modified = odi
this clashes with maps that have implicit modifiers such as blighted maps that say "maps item quantity mODIfiers also affect ___" 

Upon further investigation conquerer maps do not have this issue, they don't say modified, only blighted maps have the problem. not sure how relevant that is

**Comment by veiset** [comment]
I added 'maps item quantity modifiers also affect' as something that maps can roll, I am not quite happy with the solution but it should solve the problem for now. 

Thanks for the report!
