### ISSUE TITLE
Suggestion: Map name and implicit regex

### ISSUE THREAD

**Issue by AcclaimedAP** [veiset/poe-vendor-string#91]
Use cases are if you want to quickly glimse kirac store or possibly own stash tab for some specific implicit modifiers or to highlight certain maps you want.

I am aware the use cases are few especially if you're looking for influenced maps/unique maps, as those stand out generally, however I do not recall implicit modifiers like strong boxes, expedition, etc for the most part stand out drastically. This seems mostly valuable for SSF, where simply trading is not an option and kirac's shop is especially juicy sometimes.

**Comment by veiset** [comment]
Thanks. Kirac implicit matching be live in a few minutes.
