### ISSUE TITLE
Small issue with flasks "Only match prefix with the highest level"

### ISSUE THREAD

**Issue by GabrielB-Norway** [veiset/poe-vendor-string#95]
When you enable this prefix you only match T1 "Reduced Duration - Increased Effect" but the "Reduced Duration - Increased Effect" is always 25% increased and usually only used with Mageblood flasks so unlike every other modifier you don't actually care if it's T1 or T6 because the positive gain is always 100% the same. 

Would be nice to have an option where you ignore level of specific modifiers because with this specific one you just don't care, it's very important but tier doesn't matter.

**Comment by veiset** [comment]
Is it good enough to be able to set settings for if you care about levels for prefixes and suffixes independent of each other?

**Comment by GabrielB-Norway** [comment]
> Is it good enough to be able to set settings for if you care about levels for prefixes and suffixes independent of each other?

It's an improvement, for someone only trying to roll effect flasks for use with Mageblood it's very helpful to be able to select them independently.

But for me personally it won't help, I always roll flasks with 6 different prefixes,, and for 5 of the prefixes i care a lot about tier, it's only with the 6th I don't.

**Comment by GabrielB-Norway** [comment]
Well I think just a small checkbox would work. Which says "Ignore tier for increased effect flasks". It could be right below the "Require both prefix and suffix matches". 

Because this mod is kind of special, because it's specifically used with a very popular unique item (Mageblood) with which you really want the fixed 25% increased effect, but which also lets you ignore the downsides of the mod (reduced duration). 

So I think a solution which only works for this specific flask mod would be good enough because I can't think of any other mods where you ignore the tier completely.

**Comment by veiset** [comment]
Hey, this should be live in 2 minutes. Let me know if it solves the issue or if there are any issues with the implementation.

**Comment by GabrielB-Norway** [comment]
Looks really good.

Works ingame too.
