### ISSUE TITLE
Charged Compasses

### ISSUE THREAD

**Issue by moreON** [veiset/poe-vendor-string#98]
When rolling sextants, I'd like to be able to more easily pull all of the different compasses that I'm pricing equally out of the tab that I put them all in unsorted. In that vein, being able to select a group of compass mods and get a regex that highlights all of those and none of the others would be very useful.

I think that typically, a player would be rolling either awakened or elevated sextants and not a mixture of both at the same time so being able to discern between the two in a single regex would likely be unnecessary.

**Comment by veiset** [comment]
Thanks for the suggestion and detailed use case.

You're the second person to suggest this, so this will probably be the next major feature I'll look in to implementing!

Can you give me some more context on how this is used? Am I correct in assuming:

* Roll sextant -> Charged Compass the result -> Put it in stash.
* Then you want to search your stash tab for some types of compasses based on regex

**Comment by moreON** [comment]
Yeah, the basic idea is:

* buy sextants by the hundreds (or thousands)
* roll them on watchstones
* save a selection of those on compasses that we plan to sell
* when inventory is full drop them off in a dump tab (or 5 - I have been this deep)
* repeat a bunch of times, then sort dump tabs for selling.

It's the sorting step that could use some help. For now I tend to sort one type at a time as follows:
* put enough text to select one type of compass into the highlight text box
* move those compasses into my inventory
* move those compasses into a priced tab

I'd like to be able to group all of the compass mods that I want to apply the same price to in one regex so that I can easily pick up all of the compasses that I'm pricing equally together to move to my inventory, then into the priced tab.

**Comment by Slipperyjim8** [comment]
Made the shorthand regex for my own use would be neat to see it implemented on the site.
With similar price sorting like the bestiary ones.
Not sure if this is useful or not but here's the regex I've been using.
https://pastebin.com/MW2L8c0w
Not sure if the "rs'"	Players' Vaal Skills do not apply Soul Gain Prevention one works though.
Don't know how apostrophes are handled in poe regex.

**Comment by veiset** [comment]
Good news! I had some time today to work on this.

This should be fixed by https://github.com/veiset/poe-vendor-string/pull/109, and should be live on [poe.re](https://poe.re/#/compass) just about now. 

Please do let me know if there are any bugs with it, I haven't tested it much. If anyone of you can verify that it works it would be very good! I'll also do some testing myself.

**Comment by veiset** [comment]
Your list looks good @Slipperyjim8, took some inspiration from it. I'm afraid I can't easily get price data for compasses, as I'm using the economy data from poe.ninja and it doesn't have compasses currently.
