### ISSUE TITLE
Regex Bestiary is blank? or Just me? 

### ISSUE THREAD

**Issue by Tinapay2k21** [veiset/poe-vendor-string#99]
Tested out with different devices and tried in various VPN locations. Still having the same issue
<a href='https://postimg.cc/bGSCXx2Q' target='_blank'><img src='https://i.postimg.cc/s2wthKj0/Beast-Issue.png' border='0' alt='Beast-Issue'/></a>

**Comment by veiset** [comment]
Thanks for the report. Yeah, it's waiting for economy data from poe.ninja - https://poe.ninja/economy/affliction/beasts doesn't have any data yet.

**Comment by veiset** [comment]
I'll keep an eye on this and fallback to standard economy if it doesn't get updated soon!

**Comment by Tinapay2k21** [comment]
Hey its working now. Thank so much !
